apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80         # Port on the service
      targetPort: 80    # Port on the container
      nodePort: 30001   # NodePort assigned for external access
  type: NodePort
