apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-checker
  template:
    metadata:
      labels:
        app: db-checker
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "echo DB Username is $DB_USERNAME and DB Password is $DB_PASSWORD && sleep 3600"]
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password

